// Sample post data for the blog UI kit. Three posts mirror the three templates.

window.POSTS = [
  {
    slug: "like-a-ragged-prayer",
    title: "Like a Ragged Prayer",
    dek: "Some interesting stuff from Alexandra Alter on how AI is disrupting the romance novel industry.",
    author: { name: "David Gérouville-Farrell", initials: "D.G-F." },
    date: "2026-02-15",
    dateLong: "FEB 15, 2026",
    read: "6 MIN READ",
    readShort: "6′",
    tags: ["AI", "CREATIVE-INDUSTRIES", "FEATURE"],
    toc: [
      "Not the reaction you'd expect",
      "The relentless pull of the mean",
      "Two game industries",
    ],
    body: [
      { type: "p", text: "I was expecting to hear a story about how threatened romance novelists feel. I was expecting to hear about how unethical it is that AI trained on all of their creative works. But there was a lot more nuance than I anticipated, and there are a couple of interesting things worth sharing." },
      { type: "p", text: "The romance writing community didn't seem to show the same pattern I typically see in other creative communities — at least not <a href=\"#\">uniformly</a>. Some writers were enthusiastic about using AI for novel writing." },
      { type: "h2", text: "Not the reaction you'd expect" },
      { type: "p", text: "What surprised me was the calm. Most of the writers I read had already absorbed the news cycle and moved on to a more practical question: what does the day-to-day of writing look like when the cheap floor of \"competent prose\" drops out?" },
      { type: "quote", text: "I see the write is still truncating. Let me try a different approach — I'll use Python to write the file." },
      { type: "p", text: "The interesting move was that competent stopped being a goal. Several writers I spoke with had reframed their work as the parts a model couldn't yet do — the texture of a regional dialect, the specific way a character avoids saying something." },
      { type: "h2", text: "The relentless pull of the mean" },
      { type: "p", text: "Once a tool flattens the floor, the average reader's expectations rise. The ceiling of what's competent stays where it was, but the gap between average and excellent compresses fast. This is the part nobody seemed thrilled about, and the part everyone agreed was real." },
      { type: "code", lang: "PYTHON", text: "options = ClaudeAgentOptions(\n    allowed_tools=[\"Read\", \"Write\", \"Edit\", \"Glob\", \"Grep\"],\n    can_use_tool=handle_tool_permission,\n)" },
      { type: "fig", caption: "We want more giraffes and fewer snakes" },
      { type: "h2", text: "Two game industries" },
      { type: "p", text: "There seem to be two industries forming inside what used to be one. The first sells volume; the second sells voice. The first will compete on price, the second on attention. Neither is obviously the loser." },
    ],
  },
  {
    slug: "the-mean-and-the-message",
    title: "The Mean and the Message",
    dek: "When the floor moves up, the median gets louder. A note on signal compression in creative output.",
    author: { name: "David Gérouville-Farrell", initials: "D.G-F." },
    date: "2026-02-02",
    dateLong: "FEB 02, 2026",
    read: "9 MIN READ",
    readShort: "9′",
    tags: ["ESSAY", "AI"],
    toc: ["What changed", "Two compressions", "What it costs"],
    body: [
      { type: "p", text: "A short essay on what happens to the perceived quality of creative work once the cheap version becomes universally good." },
    ],
  },
  {
    slug: "a-working-notebook",
    title: "A Working Notebook",
    dek: "Why the new version of this site reads like a text editor rather than a magazine.",
    author: { name: "David Gérouville-Farrell", initials: "D.G-F." },
    date: "2026-01-18",
    dateLong: "JAN 18, 2026",
    read: "4 MIN READ",
    readShort: "4′",
    tags: ["META", "DESIGN"],
    toc: ["The rail", "The accent", "The corner"],
    body: [
      { type: "p", text: "Notes on the redesign. The rail. The accent. The corner. Three decisions, each load-bearing." },
    ],
  },
];
