#!/usr/bin/env python3
"""
Download every Google Font referenced across the Paidia Design Systems bundle,
write a local fonts.css with all @font-face rules pointing at relative paths.
Then replace the Google Fonts <link> in every HTML file with the local one.
"""
import re, os, sys, urllib.request, urllib.parse, hashlib
from pathlib import Path

ROOT = Path("/Users/david/projects/DesignSystems/PaidiaConsulting")
FONTS_DIR = ROOT / "fonts"
FONTS_DIR.mkdir(exist_ok=True)

# A Chrome UA so Google Fonts serves modern woff2 (otherwise gets woff/ttf)
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# Single CSS request that covers EVERY family used across the bundle.
# Generous weight ranges so we never hit a missing weight when prototyping.
GF_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Archivo:ital,wght@0,100..900;1,100..900"
    "&family=Archivo+Black"
    "&family=Space+Grotesk:wght@300..700"
    "&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800"
    "&family=Fraunces:ital,opsz,wght@0,9..144,100..900;1,9..144,100..900"
    "&family=Geist:wght@100..900"
    "&family=Geist+Mono:wght@100..900"
    "&family=Instrument+Serif:ital@0;1"
    "&display=swap"
)

def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()

print(f"Fetching Google Fonts CSS …")
css_bytes = fetch(GF_URL)
css = css_bytes.decode("utf-8")
print(f"  got {len(css)} bytes of CSS")

# Find every src: url(...) reference inside the CSS
url_re = re.compile(r'url\((https://fonts\.gstatic\.com/[^)]+)\)')
urls = sorted(set(url_re.findall(css)))
print(f"  found {len(urls)} unique font file URLs")

# Download each one, store under fonts/<family>/<basename>
mapping = {}  # remote URL -> local relative path (relative to ROOT)
for i, u in enumerate(urls, 1):
    parsed = urllib.parse.urlparse(u)
    # path looks like /s/archivo/v19/k3kPo8UDI-1M0wlSV9XAw6lQkqWY8Q83vU.woff2
    parts = parsed.path.strip("/").split("/")
    family = parts[1] if len(parts) > 1 else "misc"
    basename = parts[-1]
    out_dir = FONTS_DIR / family
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / basename
    rel_path = f"fonts/{family}/{basename}"
    mapping[u] = rel_path
    if out_file.exists() and out_file.stat().st_size > 0:
        print(f"  [{i:>3}/{len(urls)}] cached  {family}/{basename}")
        continue
    try:
        data = fetch(u)
        out_file.write_bytes(data)
        print(f"  [{i:>3}/{len(urls)}] downloaded {family}/{basename} ({len(data):,} bytes)")
    except Exception as e:
        print(f"  [{i:>3}/{len(urls)}] FAILED   {u}: {e}")

# Rewrite the CSS so url(https://fonts.gstatic.com/...) -> url(fonts/family/file.woff2)
def rewrite(m):
    u = m.group(1)
    rel = mapping.get(u, u)
    return f'url({rel})'

local_css = url_re.sub(rewrite, css)

# Add a small banner at the top
banner = (
    "/* Paidia Design Systems — local fonts.css\n"
    " * Generated by /tmp/download-fonts.py\n"
    " * Sourced from Google Fonts; bundled here for offline use.\n"
    " * Includes: Archivo, Archivo Black, Space Grotesk, JetBrains Mono,\n"
    " *           Fraunces (variable, italic + roman), Geist, Geist Mono,\n"
    " *           Instrument Serif.\n"
    " */\n\n"
)
out_css_path = ROOT / "fonts.css"
out_css_path.write_text(banner + local_css)
print(f"\n✓ Wrote {out_css_path.relative_to(ROOT)} ({len(local_css):,} bytes)")
print(f"✓ Total fonts directory: {sum(f.stat().st_size for f in FONTS_DIR.rglob('*') if f.is_file()):,} bytes")
